# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mashahed/projects/cva6/cva6/corev_apu/fpga/ariane.runs/synth_1/ariane_xilinx.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-75256-ubuntu/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-4480} -limit 1000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[Synth 8-5858]}  -new_severity {INFO} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mashahed/projects/cva6/cva6/corev_apu/fpga/ariane.cache/wt [current_project]
set_property parent.project_path /home/mashahed/projects/cva6/cva6/corev_apu/fpga/ariane.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo /home/mashahed/projects/cva6/cva6/corev_apu/fpga/ariane.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_sd_bridge/include
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/include
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/include
  /home/mashahed/projects/cva6/cva6/corev_apu/register_interface/include
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/include/common_cells/registers.svh
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/genesysii.svh
}
set_property file_type "Verilog Header" [get_files /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/include/common_cells/registers.svh]
set_property is_global_include true [get_files /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/include/common_cells/registers.svh]
set_property file_type "Verilog Header" [get_files /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/genesysii.svh]
set_property is_global_include true [get_files /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/genesysii.svh]
read_verilog -library xil_defaultlib -sv {
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga-support/rtl/SyncSpRamBeNx64.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/cf_math_pkg.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/addr_decode.sv
  /home/mashahed/projects/cva6/cva6/core/include/cv64a6_imafdc_sv39_config_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/include/riscv_pkg.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dm_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/include/ariane_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/alu.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/amo_alu.sv
  /home/mashahed/projects/cva6/cva6/core/amo_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_timer/apb_timer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/register_interface/src/apb_to_reg.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/include/ariane_axi_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/include/cvxif_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/ariane.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/tb/ariane_soc_pkg.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/tb/ariane_axi_soc_pkg.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane_peripherals_xilinx.sv
  /home/mashahed/projects/cva6/cva6/core/ariane_regfile_ff.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi2apb/src/axi2apb_64_32.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi_mem_if/src/axi2mem.sv
  /home/mashahed/projects/cva6/cva6/core/axi_adapter.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_ar_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_atop_filter.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_aw_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_b_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_demux.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_err_slv.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_id_prepend.sv
  /home/mashahed/projects/cva6/cva6/core/include/axi_intf.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/clint/axi_lite_interface.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_mux.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_r_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_res_tbl.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
  /home/mashahed/projects/cva6/cva6/core/axi_shim.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_single_slice.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/axi_slice/src/axi_w_buffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/axi/src/axi_xbar.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/axis_gmii_rx.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/axis_gmii_tx.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/bht.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/bootrom/bootrom_32.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/bootrom/bootrom_64.sv
  /home/mashahed/projects/cva6/cva6/core/branch_unit.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/btb.sv
  /home/mashahed/projects/cva6/cva6/core/include/std_cache_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/cache_ctrl.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/cdc_2phase.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/clint/clint.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/tech_cells_generic/src/cluster_clock_inverter.sv
  /home/mashahed/projects/cva6/cva6/core/commit_stage.sv
  /home/mashahed/projects/cva6/cva6/core/compressed_decoder.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/mashahed/projects/cva6/cva6/core/controller.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/counter.sv
  /home/mashahed/projects/cva6/cva6/core/csr_buffer.sv
  /home/mashahed/projects/cva6/cva6/core/csr_regfile.sv
  /home/mashahed/projects/cva6/cva6/core/cva6.sv
  /home/mashahed/projects/cva6/cva6/core/include/wt_cache_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/cva6_icache.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
  /home/mashahed/projects/cva6/cva6/core/cvxif_example/include/cvxif_instr_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/cvxif_example/cvxif_example_coprocessor.sv
  /home/mashahed/projects/cva6/cva6/core/cvxif_fu.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/debug_rom/debug_rom.sv
  /home/mashahed/projects/cva6/cva6/core/decoder.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/delta_counter.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dm_csrs.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dm_mem.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dm_sba.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dm_top.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dmi_cdc.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dmi_jtag.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/riscv-dbg/src/dmi_jtag_tap.sv
  /home/mashahed/projects/cva6/cva6/core/dromajo_ram.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/dualmem_widen.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/dualmem_widen8.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii_fifo.sv
  /home/mashahed/projects/cva6/cva6/core/ex_stage.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/exp_backoff.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/fan_ctrl.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/deprecated/fifo_v1.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/deprecated/fifo_v2.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/fifo_v3.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_pkg.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_cast_multi.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_classifier.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_divsqrt_multi.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_fma.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_fma_multi.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_noncomp.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_opgroup_block.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_opgroup_fmt_slice.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_opgroup_multifmt_slice.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_rounding.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpnew_top.sv
  /home/mashahed/projects/cva6/cva6/core/fpu_wrap.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/framing_top.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/frontend.sv
  /home/mashahed/projects/cva6/cva6/core/id_stage.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/iddr.sv
  /home/mashahed/projects/cva6/cva6/core/cvxif_example/instr_decoder.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/instr_queue.sv
  /home/mashahed/projects/cva6/cva6/core/instr_realign.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/instr_scan.sv
  /home/mashahed/projects/cva6/cva6/core/issue_read_operands.sv
  /home/mashahed/projects/cva6/cva6/core/issue_stage.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/lfsr.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/lfsr_8bit.sv
  /home/mashahed/projects/cva6/cva6/core/load_store_unit.sv
  /home/mashahed/projects/cva6/cva6/core/load_unit.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/lzc.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/miss_handler.sv
  /home/mashahed/projects/cva6/cva6/core/mmu_sv39/mmu.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/tb/common/mock_uart.sv
  /home/mashahed/projects/cva6/cva6/core/mult.sv
  /home/mashahed/projects/cva6/cva6/core/multiplier.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/oddr.sv
  /home/mashahed/projects/cva6/cva6/core/perf_counters.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/rv_plic/rtl/plic_regmap.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/rv_plic/rtl/plic_top.sv
  /home/mashahed/projects/cva6/cva6/core/pmp/src/pmp.sv
  /home/mashahed/projects/cva6/cva6/core/pmp/src/pmp_entry.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/popcount.sv
  /home/mashahed/projects/cva6/cva6/core/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/mashahed/projects/cva6/cva6/core/mmu_sv39/ptw.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/src/tech_cells_generic/src/pulp_clock_mux2.sv
  /home/mashahed/projects/cva6/cva6/core/frontend/ras.sv
  /home/mashahed/projects/cva6/cva6/core/re_name.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/register_interface/src/reg_intf.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/rgmii_core.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/rgmii_lfsr.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/rgmii_phy_if.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/rgmii_soc.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/rr_arb_tree.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/rstgen.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/rstgen_bypass.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/rv_plic/rtl/rv_plic_gateway.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/rv_plic/rtl/rv_plic_target.sv
  /home/mashahed/projects/cva6/cva6/core/scoreboard.sv
  /home/mashahed/projects/cva6/cva6/core/serdiv.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/shift_reg.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/spill_register.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/spill_register_flushable.sv
  /home/mashahed/projects/cva6/cva6/common/local/util/sram.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane-ethernet/ssio_ddr_in.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/std_cache_subsystem.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/std_nbdcache.sv
  /home/mashahed/projects/cva6/cva6/core/store_buffer.sv
  /home/mashahed/projects/cva6/cva6/core/store_unit.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/stream_arbiter.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/stream_arbiter_flushable.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/stream_demux.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/stream_mux.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/stream_register.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/tag_cmp.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_timer/timer.sv
  /home/mashahed/projects/cva6/cva6/core/mmu_sv39/tlb.sv
  /home/mashahed/projects/cva6/cva6/common/submodules/common_cells/src/unread.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_axi_adapter.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_cache_subsystem.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_dcache.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_dcache_mem.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_dcache_missunit.sv
  /home/mashahed/projects/cva6/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/ariane_xilinx.sv
}
read_vhdl -library xil_defaultlib {
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/apb_uart.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_clock_div.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_counter.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_edge_detect.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_fifo.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_input_filter.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_input_sync.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/slib_mv_filter.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/uart_baudgen.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/uart_interrupt.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/uart_receiver.vhd
  /home/mashahed/projects/cva6/cva6/corev_apu/fpga/src/apb_uart/src/uart_transmitter.vhd
}
read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.xci
set_property used_in_synthesis false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_ooc.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.xci
set_property used_in_synthesis false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_ooc.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.srcs/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.xci
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.gen/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3/user_design/constraints/xlnx_mig_7_ddr3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3.gen/sources_1/ip/xlnx_mig_7_ddr3/xlnx_mig_7_ddr3/user_design/constraints/xlnx_mig_7_ddr3.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xci
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_ooc.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_clock_converter/xlnx_axi_clock_converter.srcs/sources_1/ip/xlnx_axi_clock_converter/xlnx_axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_clock_converter/xlnx_axi_clock_converter.gen/sources_1/ip/xlnx_axi_clock_converter/xlnx_axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_clock_converter/xlnx_axi_clock_converter.gen/sources_1/ip/xlnx_axi_clock_converter/xlnx_axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_clock_converter/xlnx_axi_clock_converter.gen/sources_1/ip/xlnx_axi_clock_converter/xlnx_axi_clock_converter_ooc.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.srcs/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xci
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_board.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.srcs/sources_1/ip/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.xci
set_property used_in_synthesis false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.gen/sources_1/ip/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.gen/sources_1/ip/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter.gen/sources_1/ip/xlnx_axi_dwidth_converter/xlnx_axi_dwidth_converter_ooc.xdc]

read_ip -quiet /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_quad_spi/xlnx_axi_quad_spi.srcs/sources_1/ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi.xci
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_quad_spi/xlnx_axi_quad_spi.gen/sources_1/ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi_board.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_quad_spi/xlnx_axi_quad_spi.gen/sources_1/ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_quad_spi/xlnx_axi_quad_spi.gen/sources_1/ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_quad_spi/xlnx_axi_quad_spi.gen/sources_1/ip/xlnx_axi_quad_spi/xlnx_axi_quad_spi_clocks.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mashahed/projects/cva6/cva6/corev_apu/fpga/constraints/genesys-2.xdc
set_property used_in_implementation false [get_files /home/mashahed/projects/cva6/cva6/corev_apu/fpga/constraints/genesys-2.xdc]

read_xdc /home/mashahed/projects/cva6/cva6/corev_apu/fpga/constraints/ariane.xdc
set_property used_in_implementation false [get_files /home/mashahed/projects/cva6/cva6/corev_apu/fpga/constraints/ariane.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ariane_xilinx -part xc7k325tffg900-2 -retiming
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ariane_xilinx.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ariane_xilinx_utilization_synth.rpt -pb ariane_xilinx_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
