# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.srcs/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xci
# IP: The module: 'xlnx_axi_gpio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.srcs/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xci
# IP: The module: 'xlnx_axi_gpio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mashahed/projects/cva6/cva6/corev_apu/fpga/xilinx/xlnx_axi_gpio/xlnx_axi_gpio.gen/sources_1/ip/xlnx_axi_gpio/xlnx_axi_gpio.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_axi_gpio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
